<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251121143341 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE roles_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE users_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE subjects_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE series_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE series_subjects_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE chapters_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE resource_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE resources_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tags_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE resource_tags_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE resource_ratings_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE exam_papers_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE solutions_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE revision_sheets_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE exercises_id_seq CASCADE');
        $this->addSql('CREATE TABLE forum_categories (name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, order_num INT NOT NULL, id UUID NOT NULL, parent_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B8C5FB2D727ACA70 ON forum_categories (parent_id)');
        $this->addSql('CREATE TABLE forum_posts (content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_solution BOOLEAN NOT NULL, id UUID NOT NULL, topic_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_90291C2D1F55203D ON forum_posts (topic_id)');
        $this->addSql('CREATE INDEX IDX_90291C2DA76ED395 ON forum_posts (user_id)');
        $this->addSql('CREATE TABLE forum_topics (title VARCHAR(255) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, view_count INT NOT NULL, is_pinned BOOLEAN NOT NULL, is_locked BOOLEAN NOT NULL, id UUID NOT NULL, category_id UUID NOT NULL, user_id UUID NOT NULL, last_post_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_895975E812469DE2 ON forum_topics (category_id)');
        $this->addSql('CREATE INDEX IDX_895975E8A76ED395 ON forum_topics (user_id)');
        $this->addSql('CREATE INDEX IDX_895975E82D053F64 ON forum_topics (last_post_id)');
        $this->addSql('CREATE TABLE practice_sessions (start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duration_minutes INT DEFAULT NULL, resources_used JSON DEFAULT NULL, id UUID NOT NULL, user_id UUID NOT NULL, subject_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9D032E16A76ED395 ON practice_sessions (user_id)');
        $this->addSql('CREATE INDEX IDX_9D032E1623EDC87 ON practice_sessions (subject_id)');
        $this->addSql('CREATE TABLE user_progress (status VARCHAR(20) NOT NULL, confidence_level INT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id UUID NOT NULL, user_id UUID NOT NULL, chapter_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C28C1646A76ED395 ON user_progress (user_id)');
        $this->addSql('CREATE INDEX IDX_C28C1646579F4768 ON user_progress (chapter_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_chapter ON user_progress (user_id, chapter_id)');
        $this->addSql('ALTER TABLE forum_categories ADD CONSTRAINT FK_B8C5FB2D727ACA70 FOREIGN KEY (parent_id) REFERENCES forum_categories (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_posts ADD CONSTRAINT FK_90291C2D1F55203D FOREIGN KEY (topic_id) REFERENCES forum_topics (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_posts ADD CONSTRAINT FK_90291C2DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_topics ADD CONSTRAINT FK_895975E812469DE2 FOREIGN KEY (category_id) REFERENCES forum_categories (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_topics ADD CONSTRAINT FK_895975E8A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_topics ADD CONSTRAINT FK_895975E82D053F64 FOREIGN KEY (last_post_id) REFERENCES forum_posts (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE practice_sessions ADD CONSTRAINT FK_9D032E16A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE practice_sessions ADD CONSTRAINT FK_9D032E1623EDC87 FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_progress ADD CONSTRAINT FK_C28C1646A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_progress ADD CONSTRAINT FK_C28C1646579F4768 FOREIGN KEY (chapter_id) REFERENCES chapters (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chapters ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE chapters ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chapters ALTER subject_id TYPE UUID');
        $this->addSql('ALTER TABLE exam_papers ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE exam_papers ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE exam_papers ALTER resource_id TYPE UUID');
        $this->addSql('ALTER INDEX exam_papers_resource_id_key RENAME TO UNIQ_24A736B089329D25');
        $this->addSql('ALTER TABLE exercises ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE exercises ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE exercises ALTER resource_id TYPE UUID');
        $this->addSql('ALTER INDEX exercises_resource_id_key RENAME TO UNIQ_FA1499189329D25');
        $this->addSql('ALTER TABLE resource_ratings ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE resource_ratings ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE resource_ratings ALTER resource_id TYPE UUID');
        $this->addSql('ALTER TABLE resource_ratings ALTER user_id TYPE UUID');
        $this->addSql('ALTER TABLE resource_ratings ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER INDEX resource_ratings_resource_id_user_id_key RENAME TO unique_resource_user_rating');
        $this->addSql('ALTER TABLE resource_tags ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE resource_tags ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE resource_tags ALTER resource_id TYPE UUID');
        $this->addSql('ALTER TABLE resource_tags ALTER tag_id TYPE UUID');
        $this->addSql('ALTER INDEX resource_tags_resource_id_tag_id_key RENAME TO unique_resource_tag');
        $this->addSql('ALTER TABLE resource_types ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE resource_types ALTER id DROP DEFAULT');
        $this->addSql('ALTER INDEX resource_types_name_key RENAME TO UNIQ_728BF3025E237E06');
        $this->addSql('ALTER TABLE resources ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE resources ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE resources ALTER type_id TYPE UUID');
        $this->addSql('ALTER TABLE resources ALTER subject_id TYPE UUID');
        $this->addSql('ALTER TABLE resources ALTER chapter_id TYPE UUID');
        $this->addSql('ALTER TABLE resources ALTER series_id TYPE UUID');
        $this->addSql('ALTER TABLE resources ALTER user_id TYPE UUID');
        $this->addSql('ALTER TABLE resources ALTER status TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE resources ALTER status DROP DEFAULT');
        $this->addSql('ALTER TABLE resources ALTER view_count DROP DEFAULT');
        $this->addSql('ALTER TABLE resources ALTER download_count DROP DEFAULT');
        $this->addSql('ALTER TABLE resources ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE resources ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE revision_sheets ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE revision_sheets ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE revision_sheets ALTER resource_id TYPE UUID');
        $this->addSql('ALTER INDEX revision_sheets_resource_id_key RENAME TO UNIQ_E3C6D3D989329D25');
        $this->addSql('ALTER TABLE roles ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE roles ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE roles ALTER permissions TYPE JSON');
        $this->addSql('ALTER TABLE roles ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER INDEX roles_name_key RENAME TO UNIQ_B63E2EC75E237E06');
        $this->addSql('ALTER TABLE series ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE series ALTER id DROP DEFAULT');
        $this->addSql('ALTER INDEX series_code_key RENAME TO UNIQ_3A10012D77153098');
        $this->addSql('ALTER TABLE series_subjects ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE series_subjects ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE series_subjects ALTER series_id TYPE UUID');
        $this->addSql('ALTER TABLE series_subjects ALTER subject_id TYPE UUID');
        $this->addSql('ALTER INDEX series_subjects_series_id_subject_id_key RENAME TO unique_series_subject');
        $this->addSql('ALTER TABLE solutions ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE solutions ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE solutions ALTER resource_id TYPE UUID');
        $this->addSql('ALTER TABLE solutions ALTER exam_paper_id TYPE UUID');
        $this->addSql('ALTER INDEX solutions_resource_id_key RENAME TO UNIQ_A90F77E89329D25');
        $this->addSql('ALTER TABLE subjects ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE subjects ALTER id DROP DEFAULT');
        $this->addSql('ALTER INDEX subjects_code_key RENAME TO UNIQ_AB25991777153098');
        $this->addSql('ALTER TABLE tags ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE tags ALTER id DROP DEFAULT');
        $this->addSql('ALTER INDEX tags_name_key RENAME TO UNIQ_6FBC94265E237E06');
        $this->addSql('ALTER TABLE users ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER role_id TYPE UUID');
        $this->addSql('ALTER TABLE users ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER status TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE users ALTER status DROP DEFAULT');
        $this->addSql('ALTER TABLE users RENAME COLUMN password_hash TO password');
        $this->addSql('ALTER INDEX users_email_key RENAME TO UNIQ_email');
        $this->addSql('ALTER INDEX users_username_key RENAME TO UNIQ_username');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE roles_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE users_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE subjects_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE series_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE series_subjects_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE chapters_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE resource_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE resources_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tags_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE resource_tags_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE resource_ratings_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exam_papers_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE solutions_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE revision_sheets_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exercises_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('ALTER TABLE forum_categories DROP CONSTRAINT FK_B8C5FB2D727ACA70');
        $this->addSql('ALTER TABLE forum_posts DROP CONSTRAINT FK_90291C2D1F55203D');
        $this->addSql('ALTER TABLE forum_posts DROP CONSTRAINT FK_90291C2DA76ED395');
        $this->addSql('ALTER TABLE forum_topics DROP CONSTRAINT FK_895975E812469DE2');
        $this->addSql('ALTER TABLE forum_topics DROP CONSTRAINT FK_895975E8A76ED395');
        $this->addSql('ALTER TABLE forum_topics DROP CONSTRAINT FK_895975E82D053F64');
        $this->addSql('ALTER TABLE practice_sessions DROP CONSTRAINT FK_9D032E16A76ED395');
        $this->addSql('ALTER TABLE practice_sessions DROP CONSTRAINT FK_9D032E1623EDC87');
        $this->addSql('ALTER TABLE user_progress DROP CONSTRAINT FK_C28C1646A76ED395');
        $this->addSql('ALTER TABLE user_progress DROP CONSTRAINT FK_C28C1646579F4768');
        $this->addSql('DROP TABLE forum_categories');
        $this->addSql('DROP TABLE forum_posts');
        $this->addSql('DROP TABLE forum_topics');
        $this->addSql('DROP TABLE practice_sessions');
        $this->addSql('DROP TABLE user_progress');
        $this->addSql('ALTER TABLE chapters ALTER id TYPE INT');
        $this->addSql('ALTER TABLE chapters ALTER id SET DEFAULT nextval(\'chapters_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chapters ALTER subject_id TYPE INT');
        $this->addSql('ALTER TABLE exam_papers ALTER id TYPE INT');
        $this->addSql('ALTER TABLE exam_papers ALTER id SET DEFAULT nextval(\'exam_papers_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE exam_papers ALTER resource_id TYPE INT');
        $this->addSql('ALTER INDEX uniq_24a736b089329d25 RENAME TO exam_papers_resource_id_key');
        $this->addSql('ALTER TABLE exercises ALTER id TYPE INT');
        $this->addSql('ALTER TABLE exercises ALTER id SET DEFAULT nextval(\'exercises_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE exercises ALTER resource_id TYPE INT');
        $this->addSql('ALTER INDEX uniq_fa1499189329d25 RENAME TO exercises_resource_id_key');
        $this->addSql('ALTER TABLE resource_ratings ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE resource_ratings ALTER id TYPE INT');
        $this->addSql('ALTER TABLE resource_ratings ALTER id SET DEFAULT nextval(\'resource_ratings_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE resource_ratings ALTER resource_id TYPE INT');
        $this->addSql('ALTER TABLE resource_ratings ALTER user_id TYPE INT');
        $this->addSql('ALTER INDEX unique_resource_user_rating RENAME TO resource_ratings_resource_id_user_id_key');
        $this->addSql('ALTER TABLE resource_tags ALTER id TYPE INT');
        $this->addSql('ALTER TABLE resource_tags ALTER id SET DEFAULT nextval(\'resource_tags_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE resource_tags ALTER resource_id TYPE INT');
        $this->addSql('ALTER TABLE resource_tags ALTER tag_id TYPE INT');
        $this->addSql('ALTER INDEX unique_resource_tag RENAME TO resource_tags_resource_id_tag_id_key');
        $this->addSql('ALTER TABLE resource_types ALTER id TYPE INT');
        $this->addSql('ALTER TABLE resource_types ALTER id SET DEFAULT nextval(\'resource_types_id_seq\'::regclass)');
        $this->addSql('ALTER INDEX uniq_728bf3025e237e06 RENAME TO resource_types_name_key');
        $this->addSql('ALTER TABLE resources ALTER status TYPE VARCHAR');
        $this->addSql('ALTER TABLE resources ALTER status SET DEFAULT \'draft\'');
        $this->addSql('ALTER TABLE resources ALTER view_count SET DEFAULT 0');
        $this->addSql('ALTER TABLE resources ALTER download_count SET DEFAULT 0');
        $this->addSql('ALTER TABLE resources ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE resources ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE resources ALTER id TYPE INT');
        $this->addSql('ALTER TABLE resources ALTER id SET DEFAULT nextval(\'resources_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE resources ALTER type_id TYPE INT');
        $this->addSql('ALTER TABLE resources ALTER subject_id TYPE INT');
        $this->addSql('ALTER TABLE resources ALTER chapter_id TYPE INT');
        $this->addSql('ALTER TABLE resources ALTER series_id TYPE INT');
        $this->addSql('ALTER TABLE resources ALTER user_id TYPE INT');
        $this->addSql('ALTER TABLE revision_sheets ALTER id TYPE INT');
        $this->addSql('ALTER TABLE revision_sheets ALTER id SET DEFAULT nextval(\'revision_sheets_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE revision_sheets ALTER resource_id TYPE INT');
        $this->addSql('ALTER INDEX uniq_e3c6d3d989329d25 RENAME TO revision_sheets_resource_id_key');
        $this->addSql('ALTER TABLE roles ALTER permissions TYPE JSONB');
        $this->addSql('ALTER TABLE roles ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE roles ALTER id TYPE INT');
        $this->addSql('ALTER TABLE roles ALTER id SET DEFAULT nextval(\'roles_id_seq\'::regclass)');
        $this->addSql('ALTER INDEX uniq_b63e2ec75e237e06 RENAME TO roles_name_key');
        $this->addSql('ALTER TABLE series ALTER id TYPE INT');
        $this->addSql('ALTER TABLE series ALTER id SET DEFAULT nextval(\'series_id_seq\'::regclass)');
        $this->addSql('ALTER INDEX uniq_3a10012d77153098 RENAME TO series_code_key');
        $this->addSql('ALTER TABLE series_subjects ALTER id TYPE INT');
        $this->addSql('ALTER TABLE series_subjects ALTER id SET DEFAULT nextval(\'series_subjects_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE series_subjects ALTER series_id TYPE INT');
        $this->addSql('ALTER TABLE series_subjects ALTER subject_id TYPE INT');
        $this->addSql('ALTER INDEX unique_series_subject RENAME TO series_subjects_series_id_subject_id_key');
        $this->addSql('ALTER TABLE solutions ALTER id TYPE INT');
        $this->addSql('ALTER TABLE solutions ALTER id SET DEFAULT nextval(\'solutions_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE solutions ALTER resource_id TYPE INT');
        $this->addSql('ALTER TABLE solutions ALTER exam_paper_id TYPE INT');
        $this->addSql('ALTER INDEX uniq_a90f77e89329d25 RENAME TO solutions_resource_id_key');
        $this->addSql('ALTER TABLE subjects ALTER id TYPE INT');
        $this->addSql('ALTER TABLE subjects ALTER id SET DEFAULT nextval(\'subjects_id_seq\'::regclass)');
        $this->addSql('ALTER INDEX uniq_ab25991777153098 RENAME TO subjects_code_key');
        $this->addSql('ALTER TABLE tags ALTER id TYPE INT');
        $this->addSql('ALTER TABLE tags ALTER id SET DEFAULT nextval(\'tags_id_seq\'::regclass)');
        $this->addSql('ALTER INDEX uniq_6fbc94265e237e06 RENAME TO tags_name_key');
        $this->addSql('ALTER TABLE users ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE users ALTER status TYPE VARCHAR');
        $this->addSql('ALTER TABLE users ALTER status SET DEFAULT \'active\'');
        $this->addSql('ALTER TABLE users ALTER id TYPE INT');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE users ALTER role_id TYPE INT');
        $this->addSql('ALTER TABLE users RENAME COLUMN password TO password_hash');
        $this->addSql('ALTER INDEX uniq_email RENAME TO users_email_key');
        $this->addSql('ALTER INDEX uniq_username RENAME TO users_username_key');
    }
}
